---
abstract: 'Dist::Zilla like MAXHQ when you build your dists'
author:
  - 'Jens Berthold <jens.berthold@jebecs.de>'
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-Author-MAXHQ
requires:
  Dist::Zilla: 5.006
  Dist::Zilla::Plugin::AutoPrereqs: 0
  Dist::Zilla::Plugin::Clean: 0
  Dist::Zilla::Plugin::ConfirmRelease: 0
  Dist::Zilla::Plugin::ExecDir: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::LatestPrereqs: 0
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::OurPkgVersion: 0
  Dist::Zilla::Plugin::Pod2Html: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::Prereqs: 0
  Dist::Zilla::Plugin::PrereqsClean: 0
  Dist::Zilla::Plugin::PromptIfStale: 0
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::ReadmeAnyFromPod: 0
  Dist::Zilla::Plugin::Test::Perl::Critic: 0
  Dist::Zilla::Plugin::TestRelease: 0
  Dist::Zilla::Role::BundleDeps: 0.001000
  File::Find::Rule: 0.33
  Moose: 2.1005
  Test::Inline: 2.213
  parent: 0.228
  perl: v5.8.8
version: 0.0100021
